"use client";

import React from "react";
import type { GitHubPRData } from "../../schemas/github";
import type { ComposerStatus, ComposerStage } from "../../types";
import { Root } from "./root";
import { Header } from "./header";
import { Editor } from "./editor";
import { Checklist } from "./checklist";
import { MetaSidebar } from "./meta-sidebar";
import { Preview } from "./preview";
import { Actions } from "./actions";
import { RejectButton } from "./reject-button";
import { ApproveButton } from "./approve-button";

export interface GitHubPRComposerProps {
  /** The PR data generated by LLM */
  data: GitHubPRData;
  /** Current state of the composer */
  status: ComposerStatus;
  /** Optional pipeline stage info */
  stages?: ComposerStage[];
  /** Callback fired upon user approval with final draft */
  onApprove?: (data: GitHubPRData) => void | Promise<void>;
  /** Callback fired when user rejects draft with revision feedback */
  onReject?: (feedback: string) => void | Promise<void>;
  /** Callback fired whenever user edits content */
  onChange?: (data: GitHubPRData) => void;
  /** Repo name to display */
  repoName?: string;
  /** Additional custom class */
  className?: string;
  /** Whether to show live PR conversation preview (default: true) */
  showPreview?: boolean;
  /** Whether to show verification checklist (default: true) */
  showChecklist?: boolean;
  /** Whether to show reviewers/labels sidebar (default: true) */
  showMetaSidebar?: boolean;
  /** Label for approve button */
  approveLabel?: string;
  /** Label for reject button */
  rejectLabel?: string;
}

export function GitHubPRComposer({
  data,
  status,
  stages,
  onApprove,
  onReject,
  onChange,
  repoName,
  className,
  showPreview = true,
  showChecklist = true,
  showMetaSidebar = true,
  approveLabel,
  rejectLabel,
}: GitHubPRComposerProps) {
  return (
    <Root
      data={data}
      status={status}
      stages={stages}
      onApprove={onApprove}
      onReject={onReject}
      onChange={onChange}
      className={className}
    >
      <Header />

      <Editor showChecklist={showChecklist} showMetaSidebar={showMetaSidebar} />

      {showPreview && <Preview repoName={repoName} />}

      <Actions>
        <RejectButton label={rejectLabel} />
        <ApproveButton label={approveLabel} />
      </Actions>
    </Root>
  );
}

// Attach compound sub-components
GitHubPRComposer.Root = Root;
GitHubPRComposer.Header = Header;
GitHubPRComposer.Editor = Editor;
GitHubPRComposer.Checklist = Checklist;
GitHubPRComposer.MetaSidebar = MetaSidebar;
GitHubPRComposer.Preview = Preview;
GitHubPRComposer.Actions = Actions;
GitHubPRComposer.RejectButton = RejectButton;
GitHubPRComposer.ApproveButton = ApproveButton;
