"use client";

import React from "react";
import type { EmailDraftData } from "../../schemas/email";
import type { ComposerStatus, ComposerStage } from "../../types";
import { Root } from "./root";
import { Header } from "./header";
import { SubjectAnalyzer } from "./subject-analyzer";
import { TokensBar } from "./tokens-bar";
import { Editor } from "./editor";
import { Preview } from "./preview";
import { Actions } from "./actions";
import { RejectButton } from "./reject-button";
import { ApproveButton } from "./approve-button";

export interface EmailOutreachComposerProps {
  /** The email draft data generated by LLM */
  data: EmailDraftData;
  /** Current state of the composer */
  status: ComposerStatus;
  /** Optional pipeline stage info */
  stages?: ComposerStage[];
  /** Callback fired upon user approval with final draft */
  onApprove?: (data: EmailDraftData) => void | Promise<void>;
  /** Callback fired when user rejects draft with revision feedback */
  onReject?: (feedback: string) => void | Promise<void>;
  /** Callback fired whenever user edits content */
  onChange?: (data: EmailDraftData) => void;
  /** Sender name to display */
  senderName?: string;
  /** Sender email to display */
  senderEmail?: string;
  /** Additional custom class */
  className?: string;
  /** Whether to show live reading pane preview (default: true) */
  showPreview?: boolean;
  /** Whether to show interactive tokens toolbar (default: true) */
  showTokens?: boolean;
  /** Whether to show subject line impact analyzer (default: true) */
  showSubjectAnalyzer?: boolean;
  /** Label for approve button */
  approveLabel?: string;
  /** Label for reject button */
  rejectLabel?: string;
}

export function EmailOutreachComposer({
  data,
  status,
  stages,
  onApprove,
  onReject,
  onChange,
  senderName = "AI Outreach Assistant",
  senderEmail = "agent@company.ai",
  className,
  showPreview = true,
  showTokens = true,
  showSubjectAnalyzer = true,
  approveLabel,
  rejectLabel,
}: EmailOutreachComposerProps) {
  return (
    <Root
      data={data}
      status={status}
      stages={stages}
      onApprove={onApprove}
      onReject={onReject}
      onChange={onChange}
      className={className}
    >
      <Header senderName={senderName} />

      <Editor showTokens={showTokens} showSubjectAnalyzer={showSubjectAnalyzer} />

      {showPreview && <Preview senderEmail={senderEmail} senderName={senderName} />}

      <Actions>
        <RejectButton label={rejectLabel} />
        <ApproveButton label={approveLabel} />
      </Actions>
    </Root>
  );
}

// Attach compound sub-components
EmailOutreachComposer.Root = Root;
EmailOutreachComposer.Header = Header;
EmailOutreachComposer.SubjectAnalyzer = SubjectAnalyzer;
EmailOutreachComposer.TokensBar = TokensBar;
EmailOutreachComposer.Editor = Editor;
EmailOutreachComposer.Preview = Preview;
EmailOutreachComposer.Actions = Actions;
EmailOutreachComposer.RejectButton = RejectButton;
EmailOutreachComposer.ApproveButton = ApproveButton;
