"use client";

import React from "react";
import type { LinkedInPostData } from "../../schemas/linkedin";
import type { ComposerStatus, ComposerStage } from "../../types";
import { Root } from "./root";
import { Header } from "./header";
import { Author, type AuthorProps } from "./author";
import { StageIndicator } from "./stage-indicator";
import { Editor } from "./editor";
import { Preview } from "./preview";
import { Actions } from "./actions";
import { CharacterCount } from "./character-count";
import { RejectButton } from "./reject-button";
import { ApproveButton } from "./approve-button";
import { HashtagBar } from "./hashtag-bar";
import { MediaDropzone } from "./media-dropzone";
import { StreamingText } from "./streaming-text";

export interface LinkedInComposerProps {
  /** The post data generated by LLM */
  data: LinkedInPostData;
  /** Current state of the composer */
  status: ComposerStatus;
  /** Optional pipeline stage info */
  stages?: ComposerStage[];
  /** Callback fired upon user approval with final draft */
  onApprove?: (data: LinkedInPostData) => void | Promise<void>;
  /** Callback fired when user rejects draft with revision feedback */
  onReject?: (feedback: string) => void | Promise<void>;
  /** Callback fired whenever user edits content */
  onChange?: (data: LinkedInPostData) => void;
  /** Author details to display in the header */
  author?: AuthorProps;
  /** Additional custom class */
  className?: string;
  /** Whether to show live feed preview (default: true) */
  showPreview?: boolean;
  /** Whether to show media attachments section (default: true) */
  showMedia?: boolean;
  /** Whether to show interactive hashtag bar (default: true) */
  showHashtags?: boolean;
  /** Character limit for the post (default: 3000) */
  characterLimit?: number;
  /** Label for approve button */
  approveLabel?: string;
  /** Label for reject button */
  rejectLabel?: string;
}

export function LinkedInComposer({
  data,
  status,
  stages,
  onApprove,
  onReject,
  onChange,
  author = { name: "AI Assistant", title: "Content Composer" },
  className,
  showPreview = true,
  showMedia = true,
  showHashtags = true,
  characterLimit = 3000,
  approveLabel,
  rejectLabel,
}: LinkedInComposerProps) {
  return (
    <Root
      data={data}
      status={status}
      stages={stages}
      onApprove={onApprove}
      onReject={onReject}
      onChange={onChange}
      className={className}
    >
      <Header>
        <Author {...author} />
        {stages && stages.length > 0 && <StageIndicator />}
      </Header>

      <Editor />

      {showHashtags && <HashtagBar />}
      {showMedia && <MediaDropzone />}
      {showPreview && <Preview />}

      <Actions>
        <CharacterCount limit={characterLimit} />
        <div className="flex items-center gap-2">
          <RejectButton label={rejectLabel} />
          <ApproveButton label={approveLabel} />
        </div>
      </Actions>
    </Root>
  );
}

// Attach compound sub-components
LinkedInComposer.Root = Root;
LinkedInComposer.Header = Header;
LinkedInComposer.Author = Author;
LinkedInComposer.StageIndicator = StageIndicator;
LinkedInComposer.Editor = Editor;
LinkedInComposer.Preview = Preview;
LinkedInComposer.Actions = Actions;
LinkedInComposer.CharacterCount = CharacterCount;
LinkedInComposer.RejectButton = RejectButton;
LinkedInComposer.ApproveButton = ApproveButton;
LinkedInComposer.HashtagBar = HashtagBar;
LinkedInComposer.MediaDropzone = MediaDropzone;
LinkedInComposer.StreamingText = StreamingText;
