"use client";

import React from "react";
import type { TwitterThreadData } from "../../schemas/twitter";
import type { ComposerStatus, ComposerStage } from "../../types";
import { Root } from "./root";
import { Header } from "./header";
import { Author, type TwitterAuthorProps } from "./author";
import { Editor } from "./editor";
import { Preview } from "./preview";
import { Actions } from "./actions";
import { CountdownRing } from "./countdown-ring";
import { RejectButton } from "./reject-button";
import { ApproveButton } from "./approve-button";

export interface TwitterThreadComposerProps {
  /** The thread data generated by LLM */
  data: TwitterThreadData;
  /** Current state of the composer */
  status: ComposerStatus;
  /** Optional pipeline stage info */
  stages?: ComposerStage[];
  /** Callback fired upon user approval with final draft */
  onApprove?: (data: TwitterThreadData) => void | Promise<void>;
  /** Callback fired when user rejects draft with revision feedback */
  onReject?: (feedback: string) => void | Promise<void>;
  /** Callback fired whenever user edits content */
  onChange?: (data: TwitterThreadData) => void;
  /** Author details to display in the header & preview */
  author?: TwitterAuthorProps;
  /** Additional custom class */
  className?: string;
  /** Whether to show live thread feed preview (default: true) */
  showPreview?: boolean;
  /** Label for approve button */
  approveLabel?: string;
  /** Label for reject button */
  rejectLabel?: string;
}

export function TwitterThreadComposer({
  data,
  status,
  stages,
  onApprove,
  onReject,
  onChange,
  author = { name: "Agent Creator", handle: "ai_agent" },
  className,
  showPreview = true,
  approveLabel,
  rejectLabel,
}: TwitterThreadComposerProps) {
  return (
    <Root
      data={data}
      status={status}
      stages={stages}
      onApprove={onApprove}
      onReject={onReject}
      onChange={onChange}
      className={className}
    >
      <Header>
        <Author {...author} />
      </Header>

      <Editor />

      {showPreview && (
        <Preview
          authorName={author.name}
          authorHandle={author.handle}
          authorAvatar={author.avatar}
        />
      )}

      <Actions>
        <RejectButton label={rejectLabel} />
        <ApproveButton label={approveLabel} />
      </Actions>
    </Root>
  );
}

// Attach compound sub-components
TwitterThreadComposer.Root = Root;
TwitterThreadComposer.Header = Header;
TwitterThreadComposer.Author = Author;
TwitterThreadComposer.Editor = Editor;
TwitterThreadComposer.CountdownRing = CountdownRing;
TwitterThreadComposer.Preview = Preview;
TwitterThreadComposer.Actions = Actions;
TwitterThreadComposer.RejectButton = RejectButton;
TwitterThreadComposer.ApproveButton = ApproveButton;
